# Generated by Django 4.2.30 on 2026-07-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WasteReport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastereport",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="wastereport",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
