# Generated by Django 4.2.30 on 2026-07-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0005_municipality_city_municipality_district_and_more"),
        ("WasteReport", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastereport",
            name="assigned_municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_reports",
                to="UserAuth.municipality",
            ),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="full_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
