# Generated by Django 4.2.30 on 2026-08-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0009_workerprofile_created_at_workerprofile_is_active"),
        (
            "WasteReport",
            "0004_wastereport_assigned_municipality_wastereport_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wastereport",
            name="assigned_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_reports",
                to="UserAuth.workerprofile",
            ),
        ),
    ]
