# Generated by Django 4.2.30 on 2026-09-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteReport', '0005_wastereport_assigned_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proof_images/'),
        ),
    ]
