# Generated by Django 4.2.30 on 2026-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0002_municipality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="municipality",
            old_name="offiicial_email",
            new_name="official_email",
        ),
        migrations.AlterField(
            model_name="municipality",
            name="verification_document",
            field=models.FileField(upload_to="municipality_docs/"),
        ),
    ]
