# Generated by Django 4.2.30 on 2026-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0004_otpmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
