# Generated by Django 4.2.30 on 2026-08-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0005_municipality_city_municipality_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("public", "Public"),
                    ("municipality", "Municipality"),
                    ("worker", "Worker"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
