# Generated by Django 4.2.30 on 2026-08-25 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0006_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to="UserAuth.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="municipality_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
