# Generated by Django 4.2.30 on 2026-08-25 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0008_remove_customuser_municipality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
