# Generated by Django 4.2.30 on 2026-09-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0009_workerprofile_created_at_workerprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('public', 'Public'), ('user', 'User'), ('municipality', 'Municipality'), ('worker', 'Worker')], default='public', max_length=20),
        ),
    ]
